# This is a basic workflow to help you get started with Actions

name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_SECRET }}
          
          #Extras
          user: Mic-360
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
        
          filename: metrics.plugin.anilist.characters.svg, metrics.plugin.isocalendar.svg
          plugin_gists: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22

