name: Snake Game

on:
  schedule: # execute every 6 hours
    - cron: "* */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Become Snake
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Mic-360
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.SNAKER_TOKEN }}
